server:
  port: 9000

logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: debug

spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        root: /yangjianwu/services
  application:
    name: auth-server