logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: auth-server
  cloud:
    consul:
      host: localhost
      port: 8500

server:
  port: 9000
