server:
  port: 8080


spring:
  cloud:
    zookeeper:
      connect-string: 10.10.201.17:2181
      discovery:
        root: /yangjianwu/services
    gateway:
      routes:
      - id: admin
        uri: lb://admin
        predicates:
          - Path=/admin/**
      - id: biz
        uri: lb://qms
        predicates:
          - Path=/qms/**
  application:
    name: gateway