spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://app-resource/
          predicates:
            - Path=/user/**
    consul:
      host: localhost
      port: 8500

server:
  port: 8000
