server:
  port: 8080


spring:
  cloud:
    zookeeper:
      connect-string: 10.10.201.17:2181
      discovery:
        root: /yangjianwu/services
    gateway:
      routes:
      - id: admin
        uri: lb://admin
        predicates:
        - name: Path
          args:
            PATH: /admin/**
      - id: biz
        uri: lb://biz
        predicates:
        - name: Path
          args:
            PATH: /biz/**
  application:
    name: gateway