import gradle.kotlin.dsl.accessors._b98dfef3de91d9fe9442509845dffba2.dependencyManagement

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("io.freefair.lombok")
}

repositories {
    // 阿里巴巴 maven 仓库镜像
    maven {
        url = uri("https://maven.aliyun.com/repository/public/")
    }
    mavenLocal()
    mavenCentral()
}

dependencies {
    constraints {

    }
    implementation("com.alibaba.fastjson2:fastjson2:2.0.22")
}

