/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("top.yangjianwu.java-application-conventions")
}

dependencies {
    implementation(project(":base"))

    // https://mvnrepository.com/artifact/org.springframework.security/spring-security-oauth2-authorization-server
    implementation("org.springframework.security:spring-security-oauth2-authorization-server:1.0.1")

    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security
    implementation("org.springframework.boot:spring-boot-starter-security")

}
