spring:
  application:
    name: app-client
  cloud:
    consul:
      host: localhost
      port: 8500
  security:
    oauth2:
      client:
        registration:
          app-client-oidc:
            provider: spring
            client-id: app-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: app-client-oidc
          app-client-authorization-code:
            provider: spring
            client-id: app-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: app.read
            client-name: app-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

server:
  port: 8080
